### ISSUE TITLE
[POS] Bericht: Verkäufe Details

### ISSUE THREAD

**Issue by kennyMC** [equitania/myodoo-server-10#3]
Hallo zusammen,
wenn ich den oben genannten Bericht erstellen will bekomme ich folgende Fehlermeldung:
`Traceback (most recent call last):
  File "/opt/odoo/addons/report/controllers/main.py", line 100, in report_download
    response = self.report_routes(reportname, converter='pdf', **dict(data))
  File "/opt/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
  File "/opt/odoo/addons/report/models/report.py", line 178, in get_pdf
    html = self.with_context(context).get_html(docids, report_name, data=data)
  File "/opt/odoo/addons/report/models/report.py", line 135, in get_html
    return report_model.render_html(docids, data=data)
  File "/opt/odoo/addons/point_of_sale/models/pos_order.py", line 1004, in render_html
    data.update(self.get_sale_details(data['date_start'], data['date_stop'], configs))
  File "/opt/odoo/addons/point_of_sale/models/pos_order.py", line 984, in get_sale_details
    'currency_precision': user_currency.digits,
AttributeError: 'res.currency' object has no attribute 'digits'`

Handelt es sich hierbei um einen Konfigurationsfehler?

Vielen Dank und viele Grüße

**Comment by kennyMC** [comment]
fixed with last commit
